carpooling/carpooling/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/' , include('logPage.urls')),
    path('rider/', include('rider.urls')),
    path('driver/' , include('driver.urls'))
]

carpooling/driver/urls.py
from django.urls import path, re_path
from . import views
from rider.models import ride
app_name = 'driver'


urlpatterns = [
	path('' , views.driverHome , name = "driverHome"),
	path('driverInfo' , views.driverInfo , name = "driverInfo"),
	path('driveProcess' ,views.searchRider , name = "searchRider"),
	path('accept' ,views.acceptRider , name = "acceptRider" ),
	path('end', views.endRide , name ="endRide"),
]

carpooling/rider/urls.py
from django.urls import path,re_path
from . import views

app_name = 'rider'

# urlpatterns = [
# 	path('' , views.index , name = "index"),
# 	url(r'^(?P<album_id>[0-9]+)/$' , views.detail , name = "detail"),
# 	url(r'^(?P<album_id>[0-9]+)/favorite/$' , views.favorite , name = "favorite")
# ]

# urlpatterns = [
# 	path('' , views.IndexView.as_view() , name = "index"),
# 	url(r'^(?P<pk>[0-9]+)/$' , views.DetailView.as_view() , name = "detail"),
# 	url(r'^album/add/$', views.createAlbum.as_view() , name = "album-add")
# ]

urlpatterns = [
	path('' , views.index , name = "ride"),
	path('submit', views.rideInfo, name = "rideInfo"),
	path('processsing', views.statusUpdate, name = "statusUpdate"),
	path('success', views.rideSuccessful, name = "rideSuccessful"),
    path('dashboard/', views.dashboard, name='dashboard'),

	# path('rideRemove', views.endRide, name = "endRide"),
]

carpooling/rider/models.py
from django.db import models
from django.db import transaction
# Create your models here.
class ride(models.Model):
	userId = models.CharField(max_length = 200 , primary_key=True)
	pickUp = models.CharField(max_length = 200)
	destination = models.CharField(max_length = 200)
	complete = models.BooleanField(default=False)
	status = models.BooleanField(default=False)
	cost = models.PositiveIntegerField(default = 0)
	driverId = models.CharField(max_length = 200 , default = None, null = True)
	expectedTime = models.CharField(max_length=200, default="inf")

	def __str__(self):
		return (self.userId + " ---- " + self.destination)

	@classmethod
	def acceptRide(self , riderId , driverId):
		print("acceptRide of ride model ########################")
		success = True
		with transaction.atomic():
			r = ride.objects.select_for_update().get(pk = riderId)
			if r.status == True or r.complete == True:
				success = False
			else:
				r.driverId = driverId
				r.status = True
				r.save()

		return success

carpooling/rider/views.py
from django.shortcuts import render
from django.http import HttpResponse ,Http404
from django.template import loader
from django.shortcuts import render , get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView , UpdateView , DeleteView
from .models import ride
import numpy as np
import googlemaps 
import json

from django.core import serializers

from django.http import JsonResponse


# Create your views here.

def index(request):
	print(request.user.username)
	return render(request , "riderHome.html" , {'username' : request.user.username})
	# return HttpResponse("<h1>SUCCESS</h1>")

def rideInfo(request):
	if request.method == "POST":
		print(request.POST['userId'])
		print(request.POST['pickup'])
		print(request.POST['destination'])
		print(request.POST['latVal'])
		print(request.POST['lngVal']) 
		print(type(request.POST))
		r = ride(
			userId = request.POST['userId'], 
			pickUp = request.POST['pickup'],
			destination = request.POST['destination']
		)
		r.save()
		context ={'paramDict' : {'userId' : request.POST['userId'],'pickup' : request.POST['pickup'] , 'latVal' : request.POST['latVal'] , 
					'lngVal' : request.POST['lngVal'] , 'destination' : request.POST['destination'] }}
		#model of ride created
	return render(request , "blank.html" , context)

def statusUpdate(request):
	print("here ----------------------------------")
	id = request.GET['id']
	update =request.GET['update']
	gmaps = googlemaps.Client(key='AlzaSyNrO7TwgsPpy9CNIEsTt5VVwBzLuffHywP') 
	rideDetils = get_object_or_404(ride, pk=id)
	my_dist_1 = gmaps.distance_matrix(rideDetils.pickUp , rideDetils.destination)['rows'][0]['elements'][0]["distance"]["value"]
	my_dist_1 = my_dist_1/1000.0
	my_dist_1 = int(my_dist_1 *10)
	print("hello ----------------------------------",id)
	if rideDetils.status :
		if rideDetils.complete:
			return JsonResponse({'success':True,'driverId':rideDetils.driverId,'complete':True,'cost':my_dist_1, 'expectedTime':rideDetils.expectedTime})
		else:
			return JsonResponse({'success':True,'driverId':rideDetils.driverId,'complete':False,'cost':my_dist_1, 'expectedTime':rideDetils.expectedTime})
	return JsonResponse({'success':False,'driverId':"none",'complete':False,'cost':0, 'expectedTime':rideDetils.expectedTime})

## UNCOMMENT - if we redirect to new page after ride acceptance
def rideSuccessful(request):
	print("kkk ----------------------------------")
	if request.method == "POST":
		id = request.POST['userId']
		print("rider id", id)
		rideDetails = get_object_or_404(ride, pk=id)
	#return render(request, 'polls/results.html', {'rideDetails': rideDetails})
	return HttpResponse("<h1>SUCCESS </h1>")
def dashboard(request):
    return render(request, 'dashboard.html')


# def endRide(request):
# 	print(request.GET['id'], "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
# 	ride.objects.filter(pk=request.GET['id']).delete()
# 	print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^6")
# 	return render(request , "drive_or_ride.html" , {'user': request.GET['id']})

carpooling/rider/templates/driverHome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>CommuteX - Details</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <!-- <link href="{% static 'css/mapStyle.css' %}" rel="stylesheet" type="text/css"> -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

   <style>
      .img-container {
        text-align: center;
        display: block;
        position: relative;
        top: 10%;
      }
    </style>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map-canvas{
        height: 60%;
        width: 60%;
      }
    </style>
    <script src="{% static 'js/mapSearch.js' %}"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AlzaSyNrO7TwgsPpy9CNIEsTt5VVwBzLuffHywP &libraries=places&callback=initMap"></script>
</head>

<body class="bg-gradient-primary" style = "min-height: 100vh ; min-width: 100vh ;  background-image: url('/static/images/cab.gif');">

  <div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row" style="background-color: rgb(224, 240, 250);">
              <div class="col-lg-6 d-none d-lg-block"> 
                 <span class="img-container"> <!-- Inline parent element -->
                  <img src="{% static 'images/carpool1.jpeg' %}" alt="Carpool" align = "center"/>
                 </span>
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">All set to go!!</h1>
                  </div>
                  <form action="{% url 'driver:driverInfo' %}" name = "driverInfo" method = "post" class= "driver">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name = "destination" id="map-search" placeholder="Enter Destination">
                       <input type="hidden" id="lat" name="latVal">
                       <input type="hidden" id="lng" name="lngVal">
                       <input type="hidden" id = "userId" name = "userId" value = {{username}}>
                    </div>
                    <input type="submit" class="btn btn-primary btn-user btn-block" value="Submit">
                    <hr>
                  </form>
                  <hr>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id="map-canvas"></div>
      </div>

    </div>

  </div>
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
  {% if loginFail == True %}
   <script> alert("Password is incorrect!") </script>
  {% endif %}

  {% if userExist == False %}
   <script> alert("User Id does not exist!") </script>
  {% endif %}
</body>

</html>

carpooling/rider/templates/driverProcess.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SB Admin 2 - Login</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <!-- <link href="{% static 'css/mapStyle.css' %}" rel="stylesheet" type="text/css"> -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

   <style>
      .img-container {
        text-align: center;
        display: block;
        position: relative;
        top: 10%;
      }
    </style>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map-canvas{
        height: 60%;
        width: 60%;
      }
    </style>
    <script src="{% static 'js/getLocate.js' %}"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AlzaSyNrO7TwgsPpy9CNIEsTt5VVwBzLuffHywP &libraries=places&callback=initMap"></script>
</head>

<body class="bg-gradient-primary" style = "min-height: 100vh ; min-width: 100vh ;  background-image: url('/static/images/cab.gif');">

  <div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row" style="background-color: rgb(224, 240, 250);">
              <div class="col-lg-6 d-none d-lg-block"> 
                 <span class="img-container"> <!-- Inline parent element -->
                  <img src="{% static 'images/carpool1.jpeg' %}" alt="Carpool" align = "center"/>
                 </span>
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">All set to go!!</h1>
                  </div>
                  <form action="{% url 'driver:driverInfo' %}" name = "driverInfo" method = "post" class= "driver">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="hidden" class="form-control form-control-user" name = "destination" id="map-search" value = {{dest}}>
                       <input type="hidden" id="lat" name="latVal">
                       <input type="hidden" id="lng" name="lngVal">
                       <input type="hidden" id = "userId" name = "userId" value = {{username}}>
                    </div>
                    <input type="submit" class="btn btn-primary btn-user btn-block" value="Submit">
                    <hr>
                  </form>
                  <hr>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id="map-canvas"></div>
      </div>

    </div>

  </div>
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
  {% if loginFail == True %}
   <script> alert("Password is incorrect!") </script>
  {% endif %}

  {% if userExist == False %}
   <script> alert("User Id does not exist!") </script>
  {% endif %}
  <script type="text/javascript">
      console.log("hello ajax")

      function redirectPost(url, data) {
        var form = document.createElement('form');
        document.body.appendChild(form);
        form.method = 'post';
        form.action = url;
        for (var name in data) {
            var input = document.createElement('input');
            input.type = 'hidden';
            input.name = name;
            input.value = data[name];
            form.appendChild(input);
        }
        form.submit();
    }

      function wait(ms) { 
        const start = performance.now(); 
        while(performance.now() - start < ms); 
      }

      //getRider();
      var destPoint = '{{dest}}'
      var userID = '{{username}}'

      function getRider(callback) {
        console.log("in ajax")
        //initMap()
        console.log("after initMap")
        console.log(document.getElementById('map-search').value)

        $.ajax({
          type: "GET",
          url: '{% url "driver:searchRider"%}',
          data: {
            id : userID,
            liveLat : document.getElementById('lat').value,
            liveLong : document.getElementById('lng').value,
            destination : destPoint
          },
          datatype: "json",
          success: function(result) {
          console.log(result.rideList) //Here is the list of potential rides after algo: Iterate over this and do dynamic render
          console.log("ride Accepted")  //of Cards using JS. Aslo check for empty or something

          },
          error: function() {
              console.log("There was an error.");
              // Want to repeat AJAX call also in case of error? 
              // Then just uncomment the following two lines:
          }
      });
    
    }

      $(document).ready(function(){
             console.log("Calling getRider once more")
             setInterval(getRider,120000);
      });

      // window.addEventListener('load',function(){
      //   getRider();
      // },false);

  </script>
</body>

</html>





<!-- function getRider(callback) {
        console.log("in ajax")
        //initMap()
        console.log("after initMap")
        console.log(document.getElementById('map-search').value)
  
          $.ajax({
              type: "GET",
              url: '{% url "driver:searchRider"%}',
              data: {
                id : userID,
                liveLat : document.getElementById('lat').value,
                liveLong : document.getElementById('lng').value,
                destination : destPoint
              },
              datatype: "json",
              success: function(result) {
              var json = result['userId'];

              if(result.success) { 
                  console.log("Ride Accepted!------------------------------");
                  console.log(result.rideLi)
                  //UNCOMMENT - to redirect
                  //redirectPost('{% url "rider:rideSuccessful"%}', { userId:result['userId']})
              }else{
                  console.log("Response not yet met.");
                  //console.log(json);
                  wait(500);
                  console.log("calling again")
                  getRider();
              }
          },
          error: function() {
              console.log("There was an error.");
              // Want to repeat AJAX call also in case of error? 
              // Then just uncomment the following two lines:
              wait(1000);
              getRider();
          }
          });
      }

      window.addEventListener('load',function(){
        getRider();
      },false);
 -->